spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test:MODE=MYSQL
      maximum-pool-size: 120
    username: admin
    password:
  data:
    redis:
      host: localhost
      port: 6379

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: ture

server:
  error:
    include-stacktrace: never