server:
  port: 4201
  shutdown: graceful

spring:
  datasource:
    url: jdbc:h2:mem:test;
    username: admin
    password: 0000
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379