spring:
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  # MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/topy_promotion?characterEncoding=UTF-8&serverTimezone=UTC
    username: topy
    password: topy
    hikari:
      connection-timeout: 5000
      max-lifetime: 30000

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: kkil0421@gmail.com
    password: vbrvsamtcvlhhwie
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: ture

server:
  error:
    include-stacktrace: never